cat /dev/null > /root/UBiCauto/ubiclog/cre.log
cat /dev/null > /root/UBiCauto/ubiclog/crs.log
cat /dev/null > /root/UBiCauto/ubiclog/myc.log
cat /dev/null > /root/UBiCauto/ubiclog/myc2.log
cat /dev/null > /root/UBiCauto/ubiclog/myc3.log
cat /dev/null > /root/UBiCauto/ubiclog/nr.log
cat /dev/null > /root/UBiCauto/ubiclog/ns.log
cat /dev/null > /root/UBiCauto/ubiclog/nb.log
cat /dev/null > /root/UBiCauto/ubiclog/ns2.log
cat /dev/null > /root/UBiCauto/ubiclog/nb2.log
cat /dev/null > /root/UBiCauto/ubiclog/ns3.log
cat /dev/null > /root/UBiCauto/ubiclog/nb3.log
cat /dev/null > /root/UBiCauto/ubiclog/sc.log
